### ISSUE TITLE
Change "Open List of Experiments"

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/excel-plugin#1]
The button needs to be renamed to `Go to Conjoint.ly`. When selected, the button needs to redirect the user to https://conjointly.com/ and needs to show the [Conjoint.ly logo](https://github.com/Conjoint-ly/excel-plugin/files/4861080/Conjoint.ly.PDF.pdf).

![image](https://user-images.githubusercontent.com/13073856/86296466-2ac78580-bc3c-11ea-8572-5e018b95cffa.png)

**Comment by Harrigan-Davenport** [comment]
- [x] Change the icon to the `Macro Play` icon
