### ISSUE TITLE
Clean up the repo (after all changes are done)

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/excel-plugin#9]
Keep the https://github.com/Conjoint-ly/excel-plugin/blob/master/src/macros.bas file for reference

**Comment by Harrigan-Davenport** [comment]
- [x] Change guide so nothing refers to v2
- [x] Remove the old version of the Add In
- [x] Copy in the new VBA 
- [x] Remove any old images not used by the README.md
- [x] Resolve all issues
- [x] Add an uninstall secton
- [x] Bolding of Readme
